map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream mofin_web {
    server 127.0.0.1:4000;
}

upstream mofin_api {
    server 127.0.0.1:3000;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    client_max_body_size 50M;

    include /etc/nginx/snippets/mofin-locations.conf;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 50M;

    include /etc/nginx/snippets/mofin-locations.conf;
}
