/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FilesRouteImport } from './routes/files'
import { Route as BankAccountsRouteImport } from './routes/bank-accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnapshotsIdRouteImport } from './routes/snapshots_.$id'
import { Route as GroupsIdRouteImport } from './routes/groups_.$id'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsIdRoute = SnapshotsIdRouteImport.update({
  id: '/snapshots_/$id',
  path: '/snapshots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/groups_/$id',
  path: '/groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/files': typeof FilesRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/snapshots': typeof SnapshotsRoute
  '/transactions': typeof TransactionsRoute
  '/groups/$id': typeof GroupsIdRoute
  '/snapshots/$id': typeof SnapshotsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/files': typeof FilesRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/snapshots': typeof SnapshotsRoute
  '/transactions': typeof TransactionsRoute
  '/groups/$id': typeof GroupsIdRoute
  '/snapshots/$id': typeof SnapshotsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/files': typeof FilesRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/snapshots': typeof SnapshotsRoute
  '/transactions': typeof TransactionsRoute
  '/groups_/$id': typeof GroupsIdRoute
  '/snapshots_/$id': typeof SnapshotsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-accounts'
    | '/files'
    | '/groups'
    | '/login'
    | '/register'
    | '/snapshots'
    | '/transactions'
    | '/groups/$id'
    | '/snapshots/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-accounts'
    | '/files'
    | '/groups'
    | '/login'
    | '/register'
    | '/snapshots'
    | '/transactions'
    | '/groups/$id'
    | '/snapshots/$id'
  id:
    | '__root__'
    | '/'
    | '/bank-accounts'
    | '/files'
    | '/groups'
    | '/login'
    | '/register'
    | '/snapshots'
    | '/transactions'
    | '/groups_/$id'
    | '/snapshots_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankAccountsRoute: typeof BankAccountsRoute
  FilesRoute: typeof FilesRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SnapshotsRoute: typeof SnapshotsRoute
  TransactionsRoute: typeof TransactionsRoute
  GroupsIdRoute: typeof GroupsIdRoute
  SnapshotsIdRoute: typeof SnapshotsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts': {
      id: '/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots_/$id': {
      id: '/snapshots_/$id'
      path: '/snapshots/$id'
      fullPath: '/snapshots/$id'
      preLoaderRoute: typeof SnapshotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups_/$id': {
      id: '/groups_/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankAccountsRoute: BankAccountsRoute,
  FilesRoute: FilesRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SnapshotsRoute: SnapshotsRoute,
  TransactionsRoute: TransactionsRoute,
  GroupsIdRoute: GroupsIdRoute,
  SnapshotsIdRoute: SnapshotsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
